[package]
name = "cycles-ledger"
version = "0.1.0"
authors = ["DFINITY Stiftung <sdk@dfinity.org>"]
edition = "2021"
description = "The cycles ledger is a global ledger canister that enables principal IDs to hold cycles."
license = "Apache-2.0"
repository = "https://github.com/dfinity/cycles-ledger"
publish = false # don't publish to crates.io

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'

[dependencies]
anyhow = "1.0.75"
candid = "0.8.4"
ciborium = "0.2"
ic-cdk = { version = "0.6.0" }
ic-cdk-macros = { version = "0.6.0" }
ic-stable-structures = "0.5.0"
icrc-ledger-types = "0.1.0"
minicbor = {version = "0.19.1", features = ["alloc", "derive"]}
num-bigint = "0.4"
num-traits = "0.2"
serde = "1"
serde_bytes = "0.11"
thiserror = "1.0"

[dev-dependencies]
depositor = { path = "../depositor" }
escargot = { version = "0.5.7", features = ["print"] }
ic-test-state-machine-client = "2.2.1"
icrc1-test-env-state-machine = { git = "https://github.com/dfinity/ICRC-1", version = "0.1.0" }
icrc1-test-suite = { git = "https://github.com/dfinity/ICRC-1", version = "0.1.1" }
futures = "0.3.28"
proptest = "1.2.0"
