[package]
name = "cycles-ledger"
version = "0.1.0"
authors = ["DFINITY Stiftung <sdk@dfinity.org>"]
edition = "2021"

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'

[dependencies]
candid = "0.8.4"
ciborium = "0.2"
ic-cdk = { version = "0.6.0" }
ic-cdk-macros = { version = "0.6.0" }
ic-stable-structures = "0.5.0"
minicbor = {version = "0.19.1", features = ["alloc", "derive"]}
num-traits = "0.2"
serde = "1"
serde_bytes = "0.11"
thiserror = "1.0.40"

[dev-dependencies]
depositor = { path = "../depositor" }
escargot = { version = "0.5.7", features = ["print"] }
ic-state-machine-tests = { git = "https://github.com/dfinity/ic" }