name: Check and Test
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pocket-ic-version: [ 9.0.2 ]

    steps:
      - uses: actions/checkout@v2

      # This is needed for building state-machine-tests
      - name: Install proto
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler libprotobuf-dev

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.build }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.build }}-cargo-

      - name: Install Rust
        run: |
          rustup show

      - name: Cache StateMachine
        uses: actions/cache@v4
        with:
          path: pocket-ic
          key: ${{ matrix.pocket-ic-version }}-statemachine-binary

      - name: Download PocketIC binary
        run: ./download-pocket-ic.sh ${{ matrix.pocket-ic-version }} linux

      - name: Check Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --tests --benches -- -D clippy::all

      - name: Test
        run: cargo test
        env:
          RUST_BACKTRACE: 1
