name: Check and Test
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ic-commit: [ 6968299131311c836917f0d16d0b1b963526c9b1 ]

    steps:
      - uses: actions/checkout@v2

      # This is needed for building state-machine-tests
      - name: Install proto
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler libprotobuf-dev

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.build }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.build }}-cargo-

      - name: Install Rust
        run: |
          rustup show

      - name: Cache StateMachine
        uses: actions/cache@v2
        with:
          path: ic-test-state-machine
          key: ${{ matrix.ic-commit }}-statemachine-binary

      - name: Download StateMachine binary
        run: ./download-state-machine.sh ${{ matrix.ic-commit }} linux

      - name: Check Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --tests --benches -- -D clippy::all

      - name: Test
        run: cargo test
        env:
          RUST_BACKTRACE: 1
